# Generated by Django 4.2 on 2023-04-18 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='Standard',
            new_name='standard',
        ),
    ]
