# Generated by Django 4.2 on 2023-04-19 06:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('curriculum', '0003_comment_replyform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReplyForm',
            new_name='Reply',
        ),
    ]
